export interface APLocation {
  city: string;
  pincode: string;
  state: string;
}

export const AP_LOCATIONS: APLocation[] = [
  { city: "Kurnool", pincode: "518001", state: "Andhra Pradesh" },
  { city: "Kurnool", pincode: "518002", state: "Andhra Pradesh" },
  { city: "Kurnool", pincode: "518003", state: "Andhra Pradesh" },
  { city: "Kurnool", pincode: "518004", state: "Andhra Pradesh" },
  { city: "Kurnool", pincode: "518005", state: "Andhra Pradesh" },
  { city: "Kurnool", pincode: "518006", state: "Andhra Pradesh" },
  { city: "Tirupati", pincode: "517501", state: "Andhra Pradesh" },
  { city: "Tirupati", pincode: "517502", state: "Andhra Pradesh" },
  { city: "Tirupati", pincode: "517507", state: "Andhra Pradesh" },
  { city: "Vijayawada", pincode: "520001", state: "Andhra Pradesh" },
  { city: "Vijayawada", pincode: "520002", state: "Andhra Pradesh" },
  { city: "Vijayawada", pincode: "520010", state: "Andhra Pradesh" },
  { city: "Visakhapatnam", pincode: "530001", state: "Andhra Pradesh" },
  { city: "Visakhapatnam", pincode: "530003", state: "Andhra Pradesh" },
  { city: "Visakhapatnam", pincode: "530016", state: "Andhra Pradesh" },
  { city: "Visakhapatnam", pincode: "530048", state: "Andhra Pradesh" },
  { city: "Guntur", pincode: "522001", state: "Andhra Pradesh" },
  { city: "Guntur", pincode: "522002", state: "Andhra Pradesh" },
  { city: "Guntur", pincode: "522006", state: "Andhra Pradesh" },
  { city: "Nellore", pincode: "524001", state: "Andhra Pradesh" },
  { city: "Nellore", pincode: "524002", state: "Andhra Pradesh" },
  { city: "Nellore", pincode: "524003", state: "Andhra Pradesh" },
  { city: "Rajahmundry", pincode: "533101", state: "Andhra Pradesh" },
  { city: "Rajahmundry", pincode: "533103", state: "Andhra Pradesh" },
  { city: "Kakinada", pincode: "533001", state: "Andhra Pradesh" },
  { city: "Kakinada", pincode: "533003", state: "Andhra Pradesh" },
  { city: "Kadapa", pincode: "516001", state: "Andhra Pradesh" },
  { city: "Kadapa", pincode: "516002", state: "Andhra Pradesh" },
  { city: "Anantapur", pincode: "515001", state: "Andhra Pradesh" },
  { city: "Anantapur", pincode: "515002", state: "Andhra Pradesh" },
  { city: "Eluru", pincode: "534001", state: "Andhra Pradesh" },
  { city: "Eluru", pincode: "534006", state: "Andhra Pradesh" },
  { city: "Vizianagaram", pincode: "535001", state: "Andhra Pradesh" },
  { city: "Vizianagaram", pincode: "535002", state: "Andhra Pradesh" },
  { city: "Ongole", pincode: "523001", state: "Andhra Pradesh" },
  { city: "Chittoor", pincode: "517001", state: "Andhra Pradesh" },
  { city: "Machilipatnam", pincode: "521001", state: "Andhra Pradesh" },
  { city: "Tenali", pincode: "522201", state: "Andhra Pradesh" },
  { city: "Adoni", pincode: "518301", state: "Andhra Pradesh" },
  { city: "Proddatur", pincode: "516360", state: "Andhra Pradesh" },
  { city: "Madanapalle", pincode: "517325", state: "Andhra Pradesh" },
  { city: "Nandyal", pincode: "518501", state: "Andhra Pradesh" },
  { city: "Hindupur", pincode: "515201", state: "Andhra Pradesh" },
  { city: "Bhimavaram", pincode: "534201", state: "Andhra Pradesh" },
  { city: "Srikakulam", pincode: "532001", state: "Andhra Pradesh" },
];
