// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // DATABASE_URL must point to Supabase transaction-mode pooler (port 6543)
    // to prevent EMAXCONNSESSION errors in serverless/Next.js deployments.
    // For running `prisma migrate`, temporarily switch DATABASE_URL to the
    // direct connection URL (port 5432) or set DIRECT_URL and pass it here.
    url: process.env["DATABASE_URL"],
  },
});
